"""initial schema

Revision ID: c91d23c96bb7
Revises: 
Create Date: 2026-04-18 13:48:37.852190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91d23c96bb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer', 'vendor', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('value_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_tags_slug'), 'value_tags', ['slug'], unique=True)
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_focus_tag_id', sa.Integer(), nullable=True),
    sa.Column('rewards_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_focus_tag_id'], ['value_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('knot_merchant_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sa.String(length=64), nullable=False),
    sa.Column('knot_merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('connection_status', sa.String(length=32), nullable=False),
    sa.Column('sync_cursor', sa.String(length=512), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knot_merchant_id', name='uq_user_merchant')
    )
    op.create_index(op.f('ix_knot_merchant_accounts_external_user_id'), 'knot_merchant_accounts', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_knot_merchant_accounts_knot_merchant_id'), 'knot_merchant_accounts', ['knot_merchant_id'], unique=False)
    op.create_index(op.f('ix_knot_merchant_accounts_user_id'), 'knot_merchant_accounts', ['user_id'], unique=False)
    op.create_table('knot_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knot_transaction_id', sa.String(length=64), nullable=False),
    sa.Column('knot_merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_status', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('sub_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knot_purchases_knot_merchant_id'), 'knot_purchases', ['knot_merchant_id'], unique=False)
    op.create_index(op.f('ix_knot_purchases_knot_transaction_id'), 'knot_purchases', ['knot_transaction_id'], unique=True)
    op.create_index(op.f('ix_knot_purchases_occurred_at'), 'knot_purchases', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_knot_purchases_user_id'), 'knot_purchases', ['user_id'], unique=False)
    op.create_table('vendor_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_user_id', sa.Integer(), nullable=False),
    sa.Column('company_legal_name', sa.String(length=255), nullable=False),
    sa.Column('company_website', sa.String(length=512), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('evidence_urls', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'needs_info', 'approved', 'rejected', name='vendor_application_status'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_applications_applicant_user_id'), 'vendor_applications', ['applicant_user_id'], unique=False)
    op.create_table('vendor_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_hint', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('differentiator', sa.Text(), nullable=True),
    sa.Column('key_features', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_products_category'), 'vendor_products', ['category'], unique=False)
    op.create_index(op.f('ix_vendor_products_sku'), 'vendor_products', ['sku'], unique=False)
    op.create_index(op.f('ix_vendor_products_vendor_user_id'), 'vendor_products', ['vendor_user_id'], unique=False)
    op.create_table('customer_secondary_focuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['value_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'tag_id', name='uq_customer_secondary_focus')
    )
    op.create_index(op.f('ix_customer_secondary_focuses_profile_id'), 'customer_secondary_focuses', ['profile_id'], unique=False)
    op.create_table('knot_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sub_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['knot_purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knot_line_items_purchase_id'), 'knot_line_items', ['purchase_id'], unique=False)
    op.create_table('reward_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('account_linked', 'aligned_purchase', 'onboarding_complete', 'redemption', 'adjustment', name='reward_event_type'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('related_purchase_id', sa.Integer(), nullable=True),
    sa.Column('related_vendor_user_id', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_purchase_id'], ['knot_purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_vendor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_reward_event_dedupe')
    )
    op.create_index(op.f('ix_reward_events_event_type'), 'reward_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_reward_events_user_id'), 'reward_events', ['user_id'], unique=False)
    op.create_table('vendor_application_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['vendor_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['value_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'tag_id', name='uq_application_tag')
    )
    op.create_index(op.f('ix_vendor_application_tags_application_id'), 'vendor_application_tags', ['application_id'], unique=False)
    op.create_table('vendor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_legal_name', sa.String(length=255), nullable=False),
    sa.Column('company_website', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['vendor_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vendor_allowed_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_profile_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['value_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_profile_id'], ['vendor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_profile_id', 'tag_id', name='uq_vendor_allowed_tag')
    )
    op.create_index(op.f('ix_vendor_allowed_tags_vendor_profile_id'), 'vendor_allowed_tags', ['vendor_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_allowed_tags_vendor_profile_id'), table_name='vendor_allowed_tags')
    op.drop_table('vendor_allowed_tags')
    op.drop_table('vendor_profiles')
    op.drop_index(op.f('ix_vendor_application_tags_application_id'), table_name='vendor_application_tags')
    op.drop_table('vendor_application_tags')
    op.drop_index(op.f('ix_reward_events_user_id'), table_name='reward_events')
    op.drop_index(op.f('ix_reward_events_event_type'), table_name='reward_events')
    op.drop_table('reward_events')
    op.drop_index(op.f('ix_knot_line_items_purchase_id'), table_name='knot_line_items')
    op.drop_table('knot_line_items')
    op.drop_index(op.f('ix_customer_secondary_focuses_profile_id'), table_name='customer_secondary_focuses')
    op.drop_table('customer_secondary_focuses')
    op.drop_index(op.f('ix_vendor_products_vendor_user_id'), table_name='vendor_products')
    op.drop_index(op.f('ix_vendor_products_sku'), table_name='vendor_products')
    op.drop_index(op.f('ix_vendor_products_category'), table_name='vendor_products')
    op.drop_table('vendor_products')
    op.drop_index(op.f('ix_vendor_applications_applicant_user_id'), table_name='vendor_applications')
    op.drop_table('vendor_applications')
    op.drop_index(op.f('ix_knot_purchases_user_id'), table_name='knot_purchases')
    op.drop_index(op.f('ix_knot_purchases_occurred_at'), table_name='knot_purchases')
    op.drop_index(op.f('ix_knot_purchases_knot_transaction_id'), table_name='knot_purchases')
    op.drop_index(op.f('ix_knot_purchases_knot_merchant_id'), table_name='knot_purchases')
    op.drop_table('knot_purchases')
    op.drop_index(op.f('ix_knot_merchant_accounts_user_id'), table_name='knot_merchant_accounts')
    op.drop_index(op.f('ix_knot_merchant_accounts_knot_merchant_id'), table_name='knot_merchant_accounts')
    op.drop_index(op.f('ix_knot_merchant_accounts_external_user_id'), table_name='knot_merchant_accounts')
    op.drop_table('knot_merchant_accounts')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_value_tags_slug'), table_name='value_tags')
    op.drop_table('value_tags')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
